<a href="https://colab.research.google.com/github/Naveen148/Naveen-M/blob/main/DataPreprocessing_Assignment11_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Data.csv

**Step 1: Importing the libraries**

In [1]:

import pandas as pd
import numpy as np
import matplotlib as plt

**Step 2: Importing dataset**

In [2]:
df=pd.read_csv('/content/Data.csv')

**Step 3: Handling the missing data**

In [3]:
df.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [21]:
df.head(10)

Age   Salary  Country_Germany  Country_Spain  Purchased_Yes
0  44.0  72000.0                0              0              0
1  27.0  48000.0                0              1              1
2  30.0  54000.0                1              0              0
3  38.0  61000.0                0              1              0
4  40.0      NaN                1              0              1
5  35.0  58000.0                0              0              1
6   NaN  52000.0                0              1              0
7  48.0  79000.0                0              0              1
8  50.0  83000.0                1              0              0
9  37.0  67000.0                0              0              1

In [5]:
df.shape

(10, 4)

In [6]:
df.drop_duplicates

<bound method DataFrame.drop_duplicates of    Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes>

In [23]:
df1=df.dropna()

**Step 4: Encoding categorical data**

In [24]:
df1=pd.get_dummies(df1,drop_first=True)

In [25]:
df1.describe()

Age        Salary  Country_Germany  Country_Spain  Purchased_Yes
count   8.000000      8.000000          8.00000        8.00000       8.000000
mean   38.625000  65250.000000          0.25000        0.25000       0.500000
std     8.210403  12232.859729          0.46291        0.46291       0.534522
min    27.000000  48000.000000          0.00000        0.00000       0.000000
25%    33.750000  57000.000000          0.00000        0.00000       0.000000
50%    37.500000  64000.000000          0.00000        0.00000       0.500000
75%    45.000000  73750.000000          0.25000        0.25000       1.000000
max    50.000000  83000.000000          1.00000        1.00000       1.000000

**Step 5: Creating a dummy variable**

In [26]:
df1.corr()

Age    Salary  Country_Germany  Country_Spain  \
Age              1.000000  0.982495         0.103365  -4.604442e-01   
Salary           0.982495  1.000000         0.163980  -5.423952e-01   
Country_Germany  0.103365  0.163980         1.000000  -3.333333e-01   
Country_Spain   -0.460444 -0.542395        -0.333333   1.000000e+00   
Purchased_Yes   -0.244137 -0.196630        -0.577350   6.409876e-17   

                 Purchased_Yes  
Age              -2.441365e-01  
Salary           -1.966303e-01  
Country_Germany  -5.773503e-01  
Country_Spain     6.409876e-17  
Purchased_Yes     1.000000e+00

**Step 6: Splitting the datasets into training sets and Test sets**

In [27]:
x = df1[['Salary']].values 
y = df1['Age'].values

In [28]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

Age   Salary  Country_Germany  Country_Spain  Purchased_Yes
0  44.0  72000.0                0              0              0
1  27.0  48000.0                0              1              1
2  30.0  54000.0                1              0              0
3  38.0  61000.0                0              1              0
4  40.0      NaN                1              0              1
5  35.0  58000.0                0              0              1
6   NaN  52000.0                0              1              0
7  48.0  79000.0                0              0              1
8  50.0  83000.0                1              0              0
9  37.0  67000.0                0              0              1

**Step 7: Feature Scaling**

In [29]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train, y_train)

LogisticRegression()

In [31]:
y_pred=model.predict(x_test)


y_pred

array([48., 48.])

In [32]:
model.coef_

array([[-4.23620109e-06],
       [-1.34343768e-06],
       [ 8.53381834e-07],
       [-5.74589972e-07],
       [ 1.94688317e-06],
       [ 3.35396373e-06]])

In [33]:
model.intercept_

array([ 2.29348267e-10,  9.13145676e-11, -3.86631884e-11,  4.84994935e-11,
       -1.12630647e-10, -2.17868493e-10])

In [38]:
model.predict_proba([[2]])

array([[0.16666525, 0.16666622, 0.16666695, 0.16666648, 0.16666732,
        0.16666778]])