<a href="https://colab.research.google.com/github/Naveen148/Naveen-M/blob/main/dendrite_assg_naveen.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import numpy as np

In [28]:
data = pd.read_csv('/content/iris.csv')
data

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [29]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
col= pd.DataFrame(ohe.fit_transform(data[['species']]).toarray(),columns = data['species'].unique())
data= pd.concat([data,col], axis=1)
data.drop('species',axis=1, inplace=True)

In [30]:
df = pd.read_json('/content/algoparams_from_ui.json')
df

session_name session_description  \
algorithms                      test                test   
feature_generation              test                test   
feature_handling                test                test   
feature_reduction               test                test   
hyperparameters                 test                test   
metrics                         test                test   
probability_calibration         test                test   
session_info                    test                test   
target                          test                test   
train                           test                test   
weighting_stratergy             test                test   

                                                         design_state_data  
algorithms               {'RandomForestClassifier': {'model_name': 'Ran...  
feature_generation       {'linear_interactions': [['petal_length', 'sep...  
feature_handling         {'sepal_length': {'feature_name': 'sepal_lengt...  
feature_reduction        {'feature_reduction_method': 'Tree-based', 'nu...  
hyperparameters          {'stratergy': 'Grid Search', 'shuffle_grid': T...  
metrics                  {'optomize_model_hyperparameters_for': 'AUC', ...  
probability_calibration  {'probability_calibration_method': 'Sigmoid - ...  
session_info             {'project_id': '1', 'experiment_id': 'kkkk-11'...  
target                   {'prediction_type': 'Regression', 'target': 'p...  
train                    {'policy': 'Split the dataset', 'time_variable...  
weighting_stratergy      {'weighting_stratergy_method': 'Sample weights...

In [31]:
target = df.loc['target','design_state_data']['target']
reg = df.loc['target','design_state_data']['type']

In [32]:
feature_dic= df.loc['feature_handling','design_state_data']
feature_dic

{'sepal_length': {'feature_name': 'sepal_length',
  'is_selected': True,
  'feature_variable_type': 'numerical',
  'feature_details': {'numerical_handling': 'Keep as regular numerical feature',
   'rescaling': 'No rescaling',
   'make_derived_feats': False,
   'missing_values': 'Impute',
   'impute_with': 'Average of values',
   'impute_value': 0}},
 'sepal_width': {'feature_name': 'sepal_width',
  'is_selected': True,
  'feature_variable_type': 'numerical',
  'feature_details': {'numerical_handling': 'Keep as regular numerical feature',
   'rescaling': 'No rescaling',
   'make_derived_feats': False,
   'missing_values': 'Impute',
   'impute_with': 'custom',
   'impute_value': -1}},
 'petal_length': {'feature_name': 'petal_length',
  'is_selected': True,
  'feature_variable_type': 'numerical',
  'feature_details': {'numerical_handling': 'Keep as regular numerical feature',
   'rescaling': 'No rescaling',
   'make_derived_feats': False,
   'missing_values': 'Impute',
   'impute_with': '

In [33]:
def feature_handling(feature_handling, column_names,data):
    for col in column_names:
        try:
            if feature_handling[col]['feature_details']['impute_with'] == 'custom':
                data[col] = data[col].fillna(feature_handling[col]['feature_details']['impute_value'])
            elif feature_handling[col]['feature_details']['impute_with'] == 'Average of values': 
                data[col] = data[col].fillna(df[col].mean())
        except KeyError:
            print(col,"feature does not have 'impute_with' provided")
    return df

In [34]:
feature_handling(feature_dic, data.columns, data)

sepal_length feature does not have 'impute_with' provided
petal_length feature does not have 'impute_with' provided
Iris-setosa feature does not have 'impute_with' provided
Iris-versicolor feature does not have 'impute_with' provided
Iris-virginica feature does not have 'impute_with' provided


session_name session_description  \
algorithms                      test                test   
feature_generation              test                test   
feature_handling                test                test   
feature_reduction               test                test   
hyperparameters                 test                test   
metrics                         test                test   
probability_calibration         test                test   
session_info                    test                test   
target                          test                test   
train                           test                test   
weighting_stratergy             test                test   

                                                         design_state_data  
algorithms               {'RandomForestClassifier': {'model_name': 'Ran...  
feature_generation       {'linear_interactions': [['petal_length', 'sep...  
feature_handling         {'sepal_length': {'feature_name': 'sepal_lengt...  
feature_reduction        {'feature_reduction_method': 'Tree-based', 'nu...  
hyperparameters          {'stratergy': 'Grid Search', 'shuffle_grid': T...  
metrics                  {'optomize_model_hyperparameters_for': 'AUC', ...  
probability_calibration  {'probability_calibration_method': 'Sigmoid - ...  
session_info             {'project_id': '1', 'experiment_id': 'kkkk-11'...  
target                   {'prediction_type': 'Regression', 'target': 'p...  
train                    {'policy': 'Split the dataset', 'time_variable...  
weighting_stratergy      {'weighting_stratergy_method': 'Sample weights...

In [35]:
df.loc['algorithms']['design_state_data']

{'RandomForestClassifier': {'model_name': 'Random Forest Classifier',
  'is_selected': False,
  'min_trees': 10,
  'max_trees': 30,
  'feature_sampling_statergy': 'Default',
  'min_depth': 20,
  'max_depth': 30,
  'min_samples_per_leaf_min_value': 5,
  'min_samples_per_leaf_max_value': 50,
  'parallelism': 0},
 'RandomForestRegressor': {'model_name': 'Random Forest Regressor',
  'is_selected': True,
  'min_trees': 10,
  'max_trees': 20,
  'feature_sampling_statergy': 'Default',
  'min_depth': 20,
  'max_depth': 25,
  'min_samples_per_leaf_min_value': 5,
  'min_samples_per_leaf_max_value': 10,
  'parallelism': 0},
 'GBTClassifier': {'model_name': 'Gradient Boosted Trees',
  'is_selected': False,
  'num_of_BoostingStages': [67, 89],
  'feature_sampling_statergy': 'Fixed number',
  'learningRate': [],
  'use_deviance': True,
  'use_exponential': False,
  'fixed_number': 22,
  'min_subsample': 1,
  'max_subsample': 2,
  'min_stepsize': 0.1,
  'max_stepsize': 0.5,
  'min_iter': 20,
  'max_i

In [36]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

1.Random Forest Regressor

In [40]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV
RandomForestRegressor_params = {'model_name': 'Random Forest Regressor',
                        'is_selected': True,
                        'min_trees': 10,
                        'max_trees': 20,
                        'feature_sampling_statergy': 'Default',
                        'min_depth': 20,
                        'max_depth': 25,
                        'min_samples_per_leaf_min_value': 5,
                        'min_samples_per_leaf_max_value': 10,
                        'parallelism': 0}
rf_param_metrics = [{'n_estimators':[10,15,20]},
                    {'max_depth':[20,23,25]},
                    {'min_samples_leaf':[5,7,10]}]
from sklearn.model_selection import GridSearchCV
rf = GridSearchCV(estimator=RandomForestRegressor(),param_grid=rf_param_metrics)
rf.fit(data.drop(target, axis=1), data[target])
rf_regr = rf_gs.best_estimator_
rf_regr.predict(data.drop(target, axis=1))

array([0.25203766, 0.18188917, 0.20079499, 0.17639132, 0.24019312,
       0.32639809, 0.23358124, 0.24524127, 0.20178396, 0.16326966,
       0.27435472, 0.27656098, 0.18819043, 0.19511594, 0.26689448,
       0.27880194, 0.26689448, 0.25203766, 0.32467428, 0.26761497,
       0.31516801, 0.26641536, 0.23356181, 0.29393855, 0.29736214,
       0.23726321, 0.30470416, 0.24259117, 0.23512664, 0.22275699,
       0.20935688, 0.26476352, 0.2514528 , 0.26741721, 0.16326966,
       0.20130469, 0.25505929, 0.16326966, 0.19511594, 0.25663344,
       0.2438192 , 0.21642604, 0.20127713, 0.31239934, 0.34481582,
       0.18819043, 0.32330255, 0.20055014, 0.26366504, 0.21459588,
       1.50999252, 1.50491292, 1.55240701, 1.16753738, 1.42051541,
       1.42647619, 1.51765951, 1.04278514, 1.42016561, 1.21695448,
       1.04278514, 1.34781799, 1.18803297, 1.43172477, 1.15405298,
       1.38497472, 1.4883245 , 1.24266057, 1.41769433, 1.15086626,
       1.56265874, 1.27386192, 1.46548395, 1.42956683, 1.32252

In [42]:
rf_mse = mean_squared_error(rf_regr.predict(data.drop(target, axis=1)), data[target])

**2.GBT Regressor**

In [43]:
from sklearn.ensemble import GradientBoostingRegressor
GBTRegressor_params: {'model_name': 'Gradient Boosted Trees',
  'is_selected': False,
  'num_of_BoostingStages': [67, 89],
  'feature_sampling_statergy': 'Fixed number',
  'use_deviance': True,
  'use_exponential': False,
  'fixed_number': 22,
  'min_subsample': 1,
  'max_subsample': 2,
  'min_stepsize': 0.1,
  'max_stepsize': 0.5,
  'min_iter': 20,
  'max_iter': 40,
  'min_depth': 5,
  'max_depth': 7}
gb_param_metrics = [{'n_estimators':[67,89]},
                   {'min_samples_leaf':[1,2]},
                   {'max_depth':[5,7]},
                    {'min_impurity_decrease':[0.1,0.5]},
                    {'n_iter_no_change':[20,40]}
                   ]
gb = GridSearchCV(estimator=GradientBoostingRegressor(),param_grid=gb_param_metrics)
gb.fit(data.drop(target, axis=1), data[target])
gb_regr = gb.best_estimator_
gb_regr.predict(data.drop(target, axis=1))

array([0.2789035 , 0.24377161, 0.24377161, 0.24377161, 0.2789035 ,
       0.35006465, 0.25325078, 0.2789035 , 0.24377161, 0.24377161,
       0.2789035 , 0.28571497, 0.24377161, 0.24377161, 0.2789035 ,
       0.2789035 , 0.2789035 , 0.2789035 , 0.35006465, 0.2789035 ,
       0.35006465, 0.2789035 , 0.25325078, 0.35006465, 0.32441194,
       0.30188853, 0.31136769, 0.2789035 , 0.2789035 , 0.27623581,
       0.27623581, 0.2789035 , 0.2789035 , 0.2789035 , 0.24377161,
       0.26942433, 0.2789035 , 0.24377161, 0.24377161, 0.2789035 ,
       0.2789035 , 0.24377161, 0.24377161, 0.31136769, 0.35006465,
       0.24377161, 0.31136769, 0.24377161, 0.2789035 , 0.2789035 ,
       1.46975021, 1.46975021, 1.59404549, 1.21589644, 1.40551274,
       1.39945478, 1.5012342 , 1.00600114, 1.41540323, 1.21589644,
       1.03165386, 1.35637318, 1.21589644, 1.40934526, 1.14403308,
       1.36243114, 1.46369224, 1.21589644, 1.40551274, 1.21589644,
       1.59936947, 1.21589644, 1.52881158, 1.39945478, 1.30808

In [44]:
gb_mse = mean_squared_error(gb_regr.predict(data.drop(target, axis=1)), data[target])

**3. Linear Regression**

In [20]:
from sklearn.linear_model import LinearRegression
LinearRegression: {'model_name': 'LinearRegression',
  'is_selected': False,
  'parallelism': 2,
  'min_iter': 30,
  'max_iter': 50,
  'min_regparam': 0.5,
  'max_regparam': 0.8,
  'min_elasticnet': 0.5,
  'max_elasticnet': 0.8}
lin_reg = LinearRegression()
lin_reg.fit(df.drop(target, axis=1), df[target])
lin_reg.predict(df.drop(target, axis=1))

array([ 0.24014568,  0.1342577 ,  0.1790507 ,  0.21174828,  0.27458958,
        0.38387418,  0.26255738,  0.24874845,  0.1566694 ,  0.18332048,
        0.28574862,  0.29179513,  0.14373364,  0.11882887,  0.25046437,
        0.4320966 ,  0.28749494,  0.24014568,  0.33047841,  0.33914439,
        0.25903434,  0.31417643,  0.21611408,  0.26249417,  0.36407956,
        0.17297139,  0.27284326,  0.25476455,  0.20570178,  0.25133513,
        0.21689122,  0.21084472,  0.40457237,  0.37701772,  0.18332048,
        0.12652809,  0.17814713,  0.18332048,  0.15754256,  0.23927252,
        0.2255268 , -0.02670915,  0.2074785 ,  0.29781123,  0.43552363,
        0.14373364,  0.3632392 ,  0.21262144,  0.29522456,  0.19968567,
        1.43855549,  1.44722148,  1.47125308,  1.18731911,  1.36196848,
        1.41368114,  1.529855  ,  1.10047901,  1.37746051,  1.29152398,
        1.03932083,  1.37238078,  1.11497148,  1.44893499,  1.23127175,
        1.3697309 ,  1.47309301,  1.282858  ,  1.21649366,  1.20

In [21]:
lin_mse = mean_squared_error(lin_reg.predict(df.drop(target, axis=1)), df[target])

**4. DecisionTreeRegressor**

In [45]:
from sklearn.tree import DecisionTreeRegressor
DecisionTreeRegressor: {'model_name': 'Decision Tree',
  'is_selected': False,
  'min_depth': 4,
  'max_depth': 7,
  'use_gini': False,
  'use_entropy': True,
  'min_samples_per_leaf': [12, 6],
  'use_best': True,
  'use_random': True}

dec_tree_params = [{'max_depth':[4,5,6,7]},
              {'min_samples_leaf':[12,6]},
              {'splitter':['best','random']}]
tree_gs = GridSearchCV(DecisionTreeRegressor(),param_grid=dec_tree_params)
tree_gs.fit(data.drop(target, axis=1), data[target])
tree_reg = tree_gs.best_estimator_
tree_reg.predict(data.drop(target, axis=1))

array([0.2375    , 0.15      , 0.2       , 0.2       , 0.2375    ,
       0.34      , 0.2375    , 0.22857143, 0.2       , 0.15      ,
       0.28571429, 0.34      , 0.2       , 0.2       , 0.28571429,
       0.28571429, 0.28571429, 0.2375    , 0.34      , 0.22857143,
       0.34      , 0.22857143, 0.2375    , 0.34      , 0.34      ,
       0.15      , 0.34      , 0.22857143, 0.2375    , 0.2       ,
       0.2       , 0.28571429, 0.22857143, 0.28571429, 0.15      ,
       0.15      , 0.28571429, 0.15      , 0.2       , 0.22857143,
       0.2375    , 0.2       , 0.2       , 0.34      , 0.34      ,
       0.2       , 0.34      , 0.2       , 0.22857143, 0.2375    ,
       1.54545455, 1.54545455, 1.54545455, 1.21666667, 1.42      ,
       1.42      , 1.54545455, 1.0375    , 1.42      , 1.25555556,
       1.0375    , 1.36666667, 1.21666667, 1.42      , 1.25555556,
       1.36666667, 1.54545455, 1.25555556, 1.42      , 1.0375    ,
       1.54545455, 1.36666667, 1.42      , 1.42      , 1.36666

In [46]:
dec_tree_mse = mean_squared_error(tree_reg.predict(data.drop(target, axis=1)), data[target])

In [48]:
model_per = {}
for model in [rf_regr, gb_regr, lin_reg, tree_reg ]:
    model_per.update({str(model):[mean_absolute_error(model.predict(data.drop(target, axis=1)), data[target]), 
                                    mean_squared_error(model.predict(data.drop(target, axis=1)), data[target]),
                                   r2_score(model.predict(data.drop(target, axis=1)), data[target])]})

In [49]:
pd.DataFrame(model_per, index=['mean_abs_error','mean_squared_error','r2_score']).T.sort_values('mean_squared_error')

mean_abs_error  \
DecisionTreeRegressor(min_samples_leaf=6)                 0.104902   
RandomForestRegressor(min_samples_leaf=5)                 0.100441   
GradientBoostingRegressor(min_impurity_decrease...        0.109500   
LinearRegression()                                        0.121259   

                                                    mean_squared_error  \
DecisionTreeRegressor(min_samples_leaf=6)                     0.018461   
RandomForestRegressor(min_samples_leaf=5)                     0.018864   
GradientBoostingRegressor(min_impurity_decrease...            0.020550   
LinearRegression()                                            0.026520   

                                                    r2_score  
DecisionTreeRegressor(min_samples_leaf=6)           0.967039  
RandomForestRegressor(min_samples_leaf=5)           0.965780  
GradientBoostingRegressor(min_impurity_decrease...  0.959941  
LinearRegression()                                  0.951958